### ISSUE TITLE
Task listener gets executed before data is persisted in engine

### ISSUE THREAD

**Issue by vasicvuk** [camunda/camunda-bpm-reactor#60] opened 2017-11-13 07:40 UTC
Task listener is getting executed before the data is stored in database so there is a problem with using listeners for informing about flow of the process. For example:

If you are sending CREATE event  via EventBus (from TaskListener) to some system and this system is then Calling API to get information about the User Task's form fields, the API will return that the task not exists. After some time (150ms) the task will be created but after the event is sent.

There is a possibility of specifying timeout after receiving event  but we cannot be sure when will data actually be persisted and the call to API is safe to do.

**Comment by jangalinski** [comment] 2017-11-13 09:58
Do you have an example that shows his behavior? The call via CamundaEventBus is synchronous, so it should behave (and that's what I observed after using it a lot) like a method call ... no timeouts neede ...

**Comment by ESegundoRolon** [comment] 2018-06-13 12:41
Hi, the issue is real. If we have a TaskListener implementation, the notify method is called and the DelegateTask instance it is not persisted at this point. To check this, you could ask to camunda through REST API or using Java API if the taskID exist and the answer sometimes no, sometimes yes depending on the network status or the hardware you put to your application.

The solution I found is this:

``   Context.getCommandContext().getTransactionContext()
                .addTransactionListener(TransactionState.COMMITTED, new TransactionListener() {

                    @Override
                    public void execute(CommandContext commandContext) {
                        try {
                            //the DelegateTask is persisted now, do something
                        } catch (Exception e) {
                            e.printStackTrace();

                        }
                    }
});

**Comment by jangalinski** [comment] 2018-06-13 13:38
This is correct. But it’s not related to the extension, it’s core camunda behavior.
You cannot be sure that you can query by (task) I’d in a listener, nothing changes here when you use camundaSelector for your implementation

**Comment by jangalinski** [comment] 2019-09-24 10:18
I will close this as it is not specific for the extension and a valid workaround is provided in the comments. Thanks for that!

**Closed by jangalinski** 2019-09-24 10:18 UTC
Labels: wontfix
